# Select any one of the training Data (Value) and paste your selection as string at trainingData (Key)
# 1. multiple_bugtraps_032_moore_c8
# 2. mixed_064_moore_c16
# 3. all_064_moore_c16

trainingData: "multiple_bugtraps_032_moore_c8"

encoder:
  input: "m+"
  arch: "CNN"
  depth: 4

params:
  batch_size: 100
  num_epochs: 50
  lr: 0.001


hydra:
  job:
    chdir: False
